{
  "name": "SemanticModel",
  "compatibilityLevel": 1200,
  "model": {
    "culture": "en-GB",
    "dataSources": [
      {
        "name": "SqlServer LAPTOP-LEJVLN96 student#DW",
        "connectionString": "Provider=SQLNCLI11;Data Source=LAPTOP-LEJVLN96;Initial Catalog=student#DW;Integrated Security=SSPI;Persist Security Info=false",
        "impersonationMode": "impersonateServiceAccount",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "City",
        "columns": [
          {
            "name": "CityID",
            "dataType": "int64",
            "sourceColumn": "CityID",
            "sourceProviderType": "Integer"
          },
          {
            "name": "CityName",
            "dataType": "string",
            "sourceColumn": "CityName",
            "sourceProviderType": "WChar"
          }
        ],
        "partitions": [
          {
            "name": "City",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [Dimension].[City].* FROM [Dimension].[City] ",
              "dataSource": "SqlServer LAPTOP-LEJVLN96 student#DW"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [Dimension].[City].* FROM [Dimension].[City] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "City"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "Dimension"
          }
        ]
      },
      {
        "name": "Customer",
        "columns": [
          {
            "name": "CustomerID",
            "dataType": "int64",
            "sourceColumn": "CustomerID",
            "sourceProviderType": "Integer"
          },
          {
            "name": "CustomerName",
            "dataType": "string",
            "sourceColumn": "CustomerName",
            "sourceProviderType": "Char"
          },
          {
            "name": "DeliveryCityID",
            "dataType": "int64",
            "sourceColumn": "DeliveryCityID",
            "sourceProviderType": "Integer"
          }
        ],
        "partitions": [
          {
            "name": "Customer",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [Dimension].[Customer].* FROM [Dimension].[Customer] ",
              "dataSource": "SqlServer LAPTOP-LEJVLN96 student#DW"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [Dimension].[Customer].* FROM [Dimension].[Customer] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Customer"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "Dimension"
          }
        ]
      },
      {
        "name": "Order",
        "columns": [
          {
            "name": "OrderID",
            "dataType": "int64",
            "isUnique": true,
            "isKey": true,
            "sourceColumn": "OrderID",
            "sourceProviderType": "Integer"
          },
          {
            "name": "OrderDate",
            "dataType": "dateTime",
            "sourceColumn": "OrderDate",
            "formatString": "General Date",
            "sourceProviderType": "DBTimeStamp"
          }
        ],
        "partitions": [
          {
            "name": "Order",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [Dimension].[Order].* FROM [Dimension].[Order] ",
              "dataSource": "SqlServer LAPTOP-LEJVLN96 student#DW"
            }
          },
          {
            "name": "Order - 2013",
            "mode": "import",
            "source": {
              "type": "query",
              "query": [
                "SELECT [Dimension].[Order].* FROM [Dimension].[Order]",
                "WHERE (([OrderDate] >= N'2013-01-01 00:00:00') AND ([OrderDate] < N'2014-01-01 00:00:00'))"
              ],
              "dataSource": "SqlServer LAPTOP-LEJVLN96 student#DW"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [Dimension].[Order].* FROM [Dimension].[Order]",
                  "WHERE (([OrderDate] >= N'2013-01-01 00:00:00') AND ([OrderDate] < N'2014-01-01 00:00:00'))</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Order - 2014",
            "mode": "import",
            "source": {
              "type": "query",
              "query": [
                "SELECT [Dimension].[Order].* FROM [Dimension].[Order]",
                "WHERE (([OrderDate] >= N'2014-01-01 00:00:00') AND ([OrderDate] < N'2015-01-01 00:00:00'))"
              ],
              "dataSource": "SqlServer LAPTOP-LEJVLN96 student#DW"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [Dimension].[Order].* FROM [Dimension].[Order]",
                  "WHERE (([OrderDate] >= N'2014-01-01 00:00:00') AND ([OrderDate] < N'2015-01-01 00:00:00'))</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [Dimension].[Order].* FROM [Dimension].[Order] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Order"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "Dimension"
          }
        ]
      },
      {
        "name": "OrderLine",
        "columns": [
          {
            "name": "OrderLineID",
            "dataType": "int64",
            "isUnique": true,
            "isKey": true,
            "sourceColumn": "OrderLineID",
            "sourceProviderType": "Integer"
          },
          {
            "name": "OrderID",
            "dataType": "int64",
            "sourceColumn": "OrderID",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Quantity",
            "dataType": "int64",
            "sourceColumn": "Quantity",
            "sourceProviderType": "Integer"
          }
        ],
        "partitions": [
          {
            "name": "OrderLine",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [Dimension].[OrderLine].* FROM [Dimension].[OrderLine] ",
              "dataSource": "SqlServer LAPTOP-LEJVLN96 student#DW"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [Dimension].[OrderLine].* FROM [Dimension].[OrderLine] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "OrderLine"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "Dimension"
          }
        ]
      },
      {
        "name": "StockItem",
        "columns": [
          {
            "name": "StockItemID",
            "dataType": "int64",
            "sourceColumn": "StockItemID",
            "sourceProviderType": "Integer"
          },
          {
            "name": "StockItemName",
            "dataType": "string",
            "sourceColumn": "StockItemName",
            "sourceProviderType": "Char"
          },
          {
            "name": "SupplierID",
            "dataType": "int64",
            "sourceColumn": "SupplierID",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Brand",
            "dataType": "string",
            "sourceColumn": "Brand",
            "sourceProviderType": "Char"
          },
          {
            "name": "TaxRate",
            "dataType": "double",
            "sourceColumn": "TaxRate",
            "sourceProviderType": "Currency"
          },
          {
            "name": "UnitPrice",
            "dataType": "decimal",
            "sourceColumn": "UnitPrice",
            "formatString": "\"£\"#,0.00;-\"£\"#,0.00;\"£\"#,0.00",
            "sourceProviderType": "Currency",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"2057\" DisplayName=\"£ English (United Kingdom)\" Symbol=\"£\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "RecommendedRetailPrice",
            "dataType": "decimal",
            "sourceColumn": "RecommendedRetailPrice",
            "formatString": "\"£\"#,0.00;-\"£\"#,0.00;\"£\"#,0.00",
            "sourceProviderType": "Currency",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"2057\" DisplayName=\"£ English (United Kingdom)\" Symbol=\"£\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "StockItem",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [Dimension].[StockItem].* FROM [Dimension].[StockItem] ",
              "dataSource": "SqlServer LAPTOP-LEJVLN96 student#DW"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [Dimension].[StockItem].* FROM [Dimension].[StockItem] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "StockItem"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "Dimension"
          }
        ]
      },
      {
        "name": "Supplier",
        "columns": [
          {
            "name": "SupplierID",
            "dataType": "int64",
            "sourceColumn": "SupplierID",
            "sourceProviderType": "Integer"
          },
          {
            "name": "SupplierName",
            "dataType": "string",
            "sourceColumn": "SupplierName",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Supplier",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [Dimension].[Supplier].* FROM [Dimension].[Supplier] ",
              "dataSource": "SqlServer LAPTOP-LEJVLN96 student#DW"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [Dimension].[Supplier].* FROM [Dimension].[Supplier] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Supplier"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "Dimension"
          }
        ]
      },
      {
        "name": "Sales",
        "columns": [
          {
            "name": "SaleID",
            "dataType": "int64",
            "sourceColumn": "SaleID",
            "sourceProviderType": "Integer"
          },
          {
            "name": "StockItemID",
            "dataType": "int64",
            "sourceColumn": "StockItemID",
            "sourceProviderType": "Integer"
          },
          {
            "name": "OrderLineID",
            "dataType": "int64",
            "sourceColumn": "OrderLineID",
            "sourceProviderType": "Integer"
          },
          {
            "name": "CustomerID",
            "dataType": "int64",
            "sourceColumn": "CustomerID",
            "sourceProviderType": "Integer"
          },
          {
            "type": "calculated",
            "name": "Date",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "expression": "RELATED('Order'[OrderDate])",
            "formatString": "dd/MM/yyyy",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"2057\" Group=\"ShortDate\" FormatString=\"dd/MM/yyyy\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Total Sale",
            "dataType": "decimal",
            "isDataTypeInferred": true,
            "expression": "RELATED(OrderLine[Quantity]) * RELATED(StockItem[RecommendedRetailPrice])",
            "formatString": "\"£\"#,0.00;-\"£\"#,0.00;\"£\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"2057\" DisplayName=\"£ English (United Kingdom)\" Symbol=\"£\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Customer",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "RELATED(Customer[CustomerName])"
          },
          {
            "type": "calculated",
            "name": "Supplier",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "RELATED(Supplier[SupplierName])"
          },
          {
            "type": "calculated",
            "name": "Item",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "RELATED(StockItem[StockItemName])"
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "double",
            "isDataTypeInferred": true,
            "expression": "ROUNDUP(MONTH(Sales[Date])/3, 0)"
          },
          {
            "type": "calculated",
            "name": "Profit",
            "dataType": "decimal",
            "isDataTypeInferred": true,
            "expression": "Sales[Total Sale]-((RELATED(StockItem[UnitPrice])*(1+(RELATED(StockItem[TaxRate])/100)))*RELATED(OrderLine[Quantity]))",
            "formatString": "\"£\"#,0.00;-\"£\"#,0.00;\"£\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"2057\" DisplayName=\"£ English (United Kingdom)\" Symbol=\"£\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Sales",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [Fact].[Sales].* FROM [Fact].[Sales] ",
              "dataSource": "SqlServer LAPTOP-LEJVLN96 student#DW"
            }
          }
        ],
        "measures": [
          {
            "name": "Days Current Quarter to Date",
            "expression": "COUNTROWS(DATESQTD(Sales[Date]))"
          },
          {
            "name": "Most profitable order line",
            "expression": "MAX(Sales[Profit])",
            "formatString": "\"£\"#,0.00;-\"£\"#,0.00;\"£\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"2057\" DisplayName=\"£ English (United Kingdom)\" Symbol=\"£\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Most popular item",
            "expression": "FIRSTNONBLANK(TOPN(1, VALUES(Sales[Item]), RANKX(ALL(Sales[Item]), SUMX(RELATEDTABLE(OrderLine), OrderLine[Quantity]),,ASC)),1)"
          },
          {
            "name": "Most popular supplier",
            "expression": "FIRSTNONBLANK(TOPN(1, VALUES(Sales[Supplier]), RANKX(ALL(Sales[Supplier]), SUMX(RELATEDTABLE(OrderLine), OrderLine[Quantity]),,ASC)),1)"
          },
          {
            "name": "Days in Current Quarter",
            "expression": "COUNTROWS(DATESBETWEEN(Sales[Date], STARTOFQUARTER(LASTDATE(Sales[Date])), ENDOFQUARTER(Sales[Date])))"
          },
          {
            "name": "Distinct Sales",
            "expression": "DISTINCTCOUNT(OrderLine[OrderID])"
          },
          {
            "name": "Order Lines Count",
            "expression": "COUNT(Sales[OrderLineID])"
          },
          {
            "name": "Total Units",
            "expression": "SUM(OrderLine[Quantity])"
          },
          {
            "name": "Total Sales",
            "expression": "SUM(Sales[Total Sale])",
            "formatString": "\"£\"#,0.00;-\"£\"#,0.00;\"£\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"2057\" DisplayName=\"£ English (United Kingdom)\" Symbol=\"£\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Total Profit",
            "expression": "SUM(Sales[Profit])",
            "formatString": "\"£\"#,0.00;-\"£\"#,0.00;\"£\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"2057\" DisplayName=\"£ English (United Kingdom)\" Symbol=\"£\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Previous Quarter Profit",
            "expression": "CALCULATE([Total Profit], PREVIOUSQUARTER(Sales[Date]))",
            "formatString": "\"£\"#,0.00;-\"£\"#,0.00;\"£\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"2057\" DisplayName=\"£ English (United Kingdom)\" Symbol=\"£\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Current Quarter Profit",
            "expression": "TOTALQTD([Total Profit], Sales[Date])",
            "formatString": "\"£\"#,0.00;-\"£\"#,0.00;\"£\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"2057\" DisplayName=\"£ English (United Kingdom)\" Symbol=\"£\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Previous Quarter Profit Proportion to QTD",
            "expression": "[Previous Quarter Profit]*([Current Quarter Profit]/[Days in Current Quarter])",
            "formatString": "\"£\"#,0.00;-\"£\"#,0.00;\"£\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"2057\" DisplayName=\"£ English (United Kingdom)\" Symbol=\"£\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Previous Quarter Sales",
            "expression": "CALCULATE([Total Sales], PREVIOUSQUARTER(Sales[Date]))"
          },
          {
            "name": "Current Quarter Sales",
            "expression": "TOTALQTD([Total Sales], Sales[Date])",
            "formatString": "\"£\"#,0.00;-\"£\"#,0.00;\"£\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"2057\" DisplayName=\"£ English (United Kingdom)\" Symbol=\"£\" PositivePattern=\"0\" NegativePattern=\"1\" /></Format>"
              }
            ]
          },
          {
            "name": "Previous Quarter Sales Proportion to QTD",
            "expression": "[Previous Quarter Sales]*([Days Current Quarter to Date]/[Days in Current Quarter])"
          },
          {
            "name": "Current Quarter Sales Performance",
            "expression": "IFERROR([Current Quarter Sales]/[Previous Quarter Sales Proportion to QTD], BLANK())",
            "kpi": {
              "targetExpression": "1.1",
              "statusGraphic": "Shapes",
              "statusExpression": [
                "var x='Sales'[Current Quarter Sales Performance] return",
                "            if(ISBLANK(x),BLANK(),",
                "                    If(x<1,-1,",
                "\t                If(x<1.07,0,1)",
                "                )",
                "            )",
                "            "
              ],
              "annotations": [
                {
                  "name": "GoalType",
                  "value": "StaticValue"
                },
                {
                  "name": "KpiStatusType",
                  "value": "Linear"
                },
                {
                  "name": "KpiThresholdType",
                  "value": "Absolute"
                },
                {
                  "name": "KpiThresholdOrdering",
                  "value": "Ascending"
                },
                {
                  "name": "KpiThresholdCount",
                  "value": "2"
                },
                {
                  "name": "KpiThreshold_0",
                  "value": "1"
                },
                {
                  "name": "KpiThreshold_1",
                  "value": "1.07"
                }
              ]
            }
          },
          {
            "name": "Current Quarter Profit Performance",
            "expression": "IF([Previous Quarter Profit Proportion to QTD]<>0,([Current Quarter Profit]-[Previous Quarter Profit Proportion to QTD])/[Previous Quarter Profit Proportion to QTD], BLANK())",
            "kpi": {
              "targetExpression": "1",
              "statusGraphic": "Shapes",
              "statusExpression": [
                "var x='Sales'[Current Quarter Profit Performance] return",
                "            if(ISBLANK(x),BLANK(),",
                "                    If(x<0.82,-1,",
                "\t                If(x<0.94,0,1)",
                "                )",
                "            )",
                "            "
              ],
              "annotations": [
                {
                  "name": "GoalType",
                  "value": "StaticValue"
                },
                {
                  "name": "KpiStatusType",
                  "value": "Linear"
                },
                {
                  "name": "KpiThresholdType",
                  "value": "Absolute"
                },
                {
                  "name": "KpiThresholdOrdering",
                  "value": "Ascending"
                },
                {
                  "name": "KpiThresholdCount",
                  "value": "2"
                },
                {
                  "name": "KpiThreshold_0",
                  "value": "0.82"
                },
                {
                  "name": "KpiThreshold_1",
                  "value": "0.94"
                }
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "IDs",
            "levels": [
              {
                "name": "Sale ID",
                "ordinal": 0,
                "column": "SaleID"
              },
              {
                "name": "Stock Item ID",
                "ordinal": 1,
                "column": "StockItemID"
              },
              {
                "name": "Order Line ID",
                "ordinal": 2,
                "column": "OrderLineID"
              },
              {
                "name": "Customer ID",
                "ordinal": 3,
                "column": "CustomerID"
              }
            ]
          },
          {
            "name": "Vital Sale Data",
            "levels": [
              {
                "name": "Profit",
                "ordinal": 0,
                "column": "Profit"
              },
              {
                "name": "Total Sale",
                "ordinal": 1,
                "column": "Total Sale"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [Fact].[Sales].* FROM [Fact].[Sales] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Sales"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "Fact"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "07718767-9009-414a-b25a-1876ba3adf97",
        "fromTable": "Customer",
        "fromColumn": "DeliveryCityID",
        "toTable": "City",
        "toColumn": "CityID"
      },
      {
        "name": "71fd7d42-3b9e-47a1-a794-4475cbe0963b",
        "fromTable": "StockItem",
        "fromColumn": "SupplierID",
        "toTable": "Supplier",
        "toColumn": "SupplierID"
      },
      {
        "name": "a7bbb0bb-f604-45c0-8b97-40100d3483bd",
        "fromCardinality": "one",
        "fromTable": "Sales",
        "fromColumn": "OrderLineID",
        "toTable": "OrderLine",
        "toColumn": "OrderLineID",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "5da2638d-0038-4e11-a6bf-a538b3300c51",
        "fromTable": "Sales",
        "fromColumn": "CustomerID",
        "toTable": "Customer",
        "toColumn": "CustomerID"
      },
      {
        "name": "7e378e68-5f3a-4108-8846-9ba5239222e6",
        "fromTable": "Sales",
        "fromColumn": "StockItemID",
        "toTable": "StockItem",
        "toColumn": "StockItemID"
      },
      {
        "name": "818b8ce5-7bfe-4a23-a63a-f8e3cf467c99",
        "fromTable": "OrderLine",
        "fromColumn": "OrderID",
        "toTable": "Order",
        "toColumn": "OrderID"
      }
    ],
    "perspectives": [
      {
        "name": "Sales",
        "tables": [
          {
            "name": "OrderLine",
            "columns": [
              {
                "name": "OrderID"
              },
              {
                "name": "OrderLineID"
              },
              {
                "name": "Quantity"
              }
            ]
          },
          {
            "name": "Sales",
            "columns": [
              {
                "name": "Customer"
              },
              {
                "name": "CustomerID"
              },
              {
                "name": "Date"
              },
              {
                "name": "Item"
              },
              {
                "name": "OrderLineID"
              },
              {
                "name": "Profit"
              },
              {
                "name": "Quarter"
              },
              {
                "name": "SaleID"
              },
              {
                "name": "StockItemID"
              },
              {
                "name": "Supplier"
              },
              {
                "name": "Total Sale"
              }
            ],
            "measures": [
              {
                "name": "Current Quarter Profit"
              },
              {
                "name": "Current Quarter Sales"
              },
              {
                "name": "Days Current Quarter to Date"
              },
              {
                "name": "Days in Current Quarter"
              },
              {
                "name": "Distinct Sales"
              },
              {
                "name": "Most popular item"
              },
              {
                "name": "Most popular supplier"
              },
              {
                "name": "Most profitable order line"
              },
              {
                "name": "Order Lines Count"
              },
              {
                "name": "Previous Quarter Profit"
              },
              {
                "name": "Previous Quarter Profit Proportion to QTD"
              },
              {
                "name": "Previous Quarter Sales"
              },
              {
                "name": "Previous Quarter Sales Proportion to QTD"
              },
              {
                "name": "Total Profit"
              },
              {
                "name": "Total Sales"
              },
              {
                "name": "Total Units"
              },
              {
                "name": "Current Quarter Profit Performance"
              },
              {
                "name": "Current Quarter Sales Performance"
              }
            ]
          },
          {
            "name": "StockItem",
            "columns": [
              {
                "name": "Brand"
              },
              {
                "name": "RecommendedRetailPrice"
              },
              {
                "name": "StockItemID"
              },
              {
                "name": "StockItemName"
              },
              {
                "name": "SupplierID"
              },
              {
                "name": "TaxRate"
              },
              {
                "name": "UnitPrice"
              }
            ]
          }
        ]
      }
    ],
    "roles": [
      {
        "name": "Administrator",
        "modelPermission": "administrator",
        "members": [
          {
            "memberName": "NT SERVICE\\MSSQLServerOLAPService",
            "memberId": "S-1-5-80-2872255330-672591203-888807865-2791174282-1554802921"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "400"
      }
    ]
  },
  "id": "SemanticModel"
}